### ISSUE TITLE
graphic bug on v0.3.4

### ISSUE THREAD

**Issue by alooful** [Rosalie241/RMG#100]
Lines above all the text which weren't there on prior versions 

![image](https://user-images.githubusercontent.com/125163385/218285438-14534fd8-4ff7-4f6e-938a-41ec43e86192.png)

**Comment by Rosalie241** [comment]
are you sure it doesn't happen on i.e v0.3.3 either?

**Comment by RadikAlice** [comment]
Would also be useful to know what graphics plugin you're using, and what settings you've changed
As I've seen those sorts of seams when using GLideN64 in previous versions and upscaling the resolution too much

**Comment by Rosalie241** [comment]
Closing due to not receiving a reply and it not being RMG's fault.
