### ISSUE TITLE
Getting a weird Core Error message when playing Donkey Kong 64 (USA)

### ISSUE THREAD

**Issue by AkihitoZero5454** [Rosalie241/RMG#106]
On the first cutscene when you start a new game It'll popup up a Core Error DIV_5 by 0. When you close the message it'll still keep the game running but keep doing the error popup.

**Comment by Jj0YzL5nvJ** [comment]
mupen64plus/mupen64plus-core#684

**Comment by Rosalie241** [comment]
the UI problem should be fixed with this build: https://github.com/Rosalie241/RMG/actions/runs/4207423203

**Comment by AkihitoZero5454** [comment]
> the UI problem should be fixed with this build: https://github.com/Rosalie241/RMG/actions/runs/4207433776

Thanks

**Comment by Rosalie241** [comment]
UI fix is included in v0.3.6
