### ISSUE TITLE
Very few directories are showing as options for a ROMs directory

### ISSUE THREAD

**Issue by gisn8** [Rosalie241/RMG#107]
![image](https://user-images.githubusercontent.com/8834227/219825354-251b38de-e13c-4e92-8993-a71dcc0eecbd.png)
Very few directories are showing as options for a ROMs directory. Running on Linux Mint Cinnamon.

**Comment by Rosalie241** [comment]
Can you try the AppImage from v0.3.6 and see if it happens there too?
