### ISSUE TITLE
Autoupdate fail

### ISSUE THREAD

**Issue by Francehelder** [Rosalie241/RMG#109]
Update to 0.3.6 don't work

![image](https://user-images.githubusercontent.com/14970431/219956566-2a35393b-d223-41cf-bba3-e4bedf681703.png)

**Comment by Rosalie241** [comment]
That's sadly correct, the portable linux builds are gone and replaced by an AppImage so the updater for that broke, I'll add a note to the release notes, to solve this, download the AppImage manually and use that instead!
