### ISSUE TITLE
FlatPak GUI icons do not appear!

### ISSUE THREAD

**Issue by MInessota** [Rosalie241/RMG#110]
Rosalie's Flatpak in version 0.3.6 is missing GUI icons!
Running Flatpak on Linux Mint 20.3

![Captura de tela 2023-02-19 17:24:09](https://user-images.githubusercontent.com/28904791/219973601-fe051adf-360c-4541-8f6e-6fd2f79cd0b7.png)

**Comment by Rosalie241** [comment]
Hmm, odd, can you try going to the settings -> plugins tab -> click on 'reset to defaults' -> click save -> restart RMG?

**Comment by MInessota** [comment]
Yes it worked!

Thank you very much, I love your emulator, Rosalie is the best emulator that runs N64 on Linux (^o^)//

**Comment by Rosalie241** [comment]
I realized why this happens, I'll fix it in the code and include it in n]the next release :heart:

**Comment by Rosalie241** [comment]
Fixed in v0.3.7!
