### ISSUE TITLE
RMG 0.37 GLideN64 plugin selection language invalid

### ISSUE THREAD

**Issue by crashGG** [Rosalie241/RMG#112]
Regardless of the language selected, the interface is displayed in English.
<img width="478" alt="2023-02-23_091348" src="https://user-images.githubusercontent.com/80488411/220833002-6c31587b-c973-4e41-92bd-1886205e23d9.png">

**Comment by Rosalie241** [comment]
I can reproduce your issue but I'm uncertain how to fix it at the moment! I'll take another closer look in the near future and see what I can or cannot do!

**Comment by Rosalie241** [comment]
Fixed with https://github.com/gonetz/GLideN64/pull/2764, which'll be included in the next release!
