### ISSUE TITLE
GCN Controller directions inaccurate 

### ISSUE THREAD

**Issue by TailsGuy** [Rosalie241/RMG#114]
So, I used the GCN controller plug-in and loaded up Majora's Mask, however when I Z Target and try to go backwards, he's going to the side somewhat. There's a mechanic that if you hold directly backwards, you move much faster. I even unplugged my controller thinking it was because the deadzone was being weird, but it's definitely the emulator.

**Comment by Rosalie241** [comment]
Please try it with this ROM: https://github.com/sanni/controllertest/blob/master/N64-Port/controllertest.v64

and report it to the plugins repository instead: https://github.com/amatho/mupen64plus-input-gca
