### ISSUE TITLE
Controller Pak

### ISSUE THREAD

**Issue by spiele-tom** [Rosalie241/RMG#115]
How do I use the controller Pak function with Camebube WiiU Adapter?

**Comment by Rosalie241** [comment]
Sadly the mupen64plus-input-gca plugin doesn't support such a thing, there's already an open issue in that repository for it though which you can keep your eyes on: https://github.com/amatho/mupen64plus-input-gca/issues/13.

Sadly there isn't much I can do because Im unfamiliar with rust.
