### ISSUE TITLE
The problem of synchronizing video with sound.

### ISSUE THREAD

**Issue by SatanNintendo** [Rosalie241/RMG#118]
Hello! Thank you for the wonderful emulator "**RMG**", I like how it works.
I wanted to share one problem that I encountered playing different games on "**RMG**".
When I start playing any game, at first everything is fine, but after a few minutes, the sound starts to lag behind video, for about 1 second, this is after 10 - 15 minutes of the game. I use the video plugin "**angrylion RDP plugin**", as I like the original console picture. Perhaps I am not writing here quite correctly, if so, then I apologize, if it is true, then it would be great if it could be fixed in the future. I recorded a video example of how this happens for me.
If I leave the emulator inactive, and then reactivate it, the synchronization is restored for a while and again goes away for about 1 second, this happens in different games. Thanks for attention.

https://user-images.githubusercontent.com/10689866/222463470-ee5dfb33-050d-41b8-b2e3-d94d848d7131.mp4

**Comment by Rosalie241** [comment]
Try enabling ;synchronize audio' in audio settings -> advanced.

**Comment by SatanNintendo** [comment]
> Try enabling 'synchronize audio' in audio settings -> advanced.

Yes, indeed, it looks like it helped me!
Thank you very much for being able to tell me this.
I apologize for the concern, the issue is closed to me.
