### ISSUE TITLE
Add option to disable save file name hash

### ISSUE THREAD

**Issue by Caverns4** [Rosalie241/RMG#122]
Save files in this emulator use a system for save files where the save data file includes an 8-character hash in the save file's name, based on the ROM used to generate the save. For example, and Ocarina Of Time right might be called THE LEGEND OF ZELDA-19AF1C80.sra. While this is good for most applications and casual use, when doing something more experimental, such as modifications or testing something small, it can make the testing process much more arduous than it needs to be. An option to used non-hashed save files (I.E, THE LEGEND OF ZELDA.sra instead of THE LEGEND OF ZELDA-########.sra) would be appreciated

**Comment by Rosalie241** [comment]
I've opened a mupen64plus-core PR and made an experimental RMG branch with code to expose the setting in the GUI, please try this build: https://github.com/Rosalie241/RMG/actions/runs/4379076836/jobs/7664602954 and see the new "Save Filename Format" setting in the Core tab of the settings dialog, if you set it to "Internal ROM Name", it should work like you want it to!

**Comment by Rosalie241** [comment]
Implemented in v0.3.9

>  One more setting that might be helpful for certain users is Internal Name + Region Code

I'm not sure if that's worth the effort so the current option should be good enough for now.
