### ISSUE TITLE
The Legend Of Zelda: Majora's Mask has a problem with the Lens Of Truth.

### ISSUE THREAD

**Issue by AkihitoZero5454** [Rosalie241/RMG#128]
The Lens Of Truth will make the invisible object larger as it looks like Link is clipping to the object and it makes the ice blocks and ladders to reach the tomb to get the Goron Mask harder.

Windows 10
PC
v0.3.9
GlideN64

**Comment by RokkumanX** [comment]
That's not much information to go on to be quite honest and with vague information like this it's not exactly easy to say what would cause the issue as we know nothing about:

A. Platform (Windows or Linux)
B. System used for emulation 
C. Version of RMG used 
D. Plugins used (GlideN64, angrylion or ParaLLEl)

I recently played through the japanese version with angrylion with zero issues, as a wild guess it sounds GlideN64 related.

**Comment by Jj0YzL5nvJ** [comment]
https://imgur.com/a/sz6J1ii

![R01](https://user-images.githubusercontent.com/12230570/230501435-bbd6ce04-97b7-4f0c-9a3e-366ae4a84344.png)

**Comment by AkihitoZero5454** [comment]
> https://imgur.com/a/sz6J1ii
> 
> ![R01](https://user-images.githubusercontent.com/12230570/230501435-bbd6ce04-97b7-4f0c-9a3e-366ae4a84344.png)

Thanks! It worked!

**Comment by Rosalie241** [comment]
Yeah it's a known GLideN64 issue, what @Jj0YzL5nvJ suggested can cause issues on some drivers but it works for some, I'm glad it works!

Thank you @RokkumanX and @Jj0YzL5nvJ for helping :heart:
