### ISSUE TITLE
[Feature Request] Controller Hotkeys

### ISSUE THREAD

**Issue by OdeyDev** [Rosalie241/RMG#132]
As mentioned above, I think it would be really useful to have controller input for hotkeys. I mainly want to be able to use a button combo that closes the emulator but unfortunately it seems there are only keyboard hotkeys.

**Comment by Tartifless** [comment]
+1 for this request.

The following hotkey combo possibility with controller would be great:
- exit emulator
- pause
- save state
- load state
- screenshot

**Comment by Rosalie241** [comment]
Implemented in v0.4.2!

**Comment by Tartifless** [comment]
You are the best !

**Comment by OdeyDev** [comment]
Absolute legend
