### ISSUE TITLE
Error when opening the emulator

### ISSUE THREAD

**Issue by ExGuestCJ** [Rosalie241/RMG#133]
When I try to open RMG.exe I always get an error, even when I reinstall it

**Comment by Rosalie241** [comment]
I'm unable to help you when you don't tell me what platform you're on and what error you're getting.

**Comment by ExGuestCJ** [comment]
im on windows 8.1 and i get an error about a missing dll file or something
(im not using my computer when im writing this)

**Comment by Rosalie241** [comment]
Qt6 doesn't support EOL operating systems including windows 7 and windows 8, upgrade to windows 10 (which is free and superior in many ways to windows 8) and it'll work fine.
