### ISSUE TITLE
Mupen64 FZ Saves?

### ISSUE THREAD

**Issue by GAMECUBE-N64** [Rosalie241/RMG#139]
Been Using Mupen64 on Android from way back to present on Mupen64 and then Mupen64 FZ. I have game saves on  Mupen64 FZ for every Nintendo64 game rom. Is there a way to use either Autosaves, Slot Saves, Sram Data, or User Saves From Mupen64 FZ in Rosalie's64 on Steam Deck? Thank You! :)

**Comment by Rosalie241** [comment]
I asked fzurita and they said that SRAM saves should be compatible, so you can copy those files to the save sram path specified in settings -> directories!

**Comment by GAMECUBE-N64** [comment]
Thank You So Much! That means a lot. Perhaps day You can have Game Covers and allow Custom Game Covers on Your emulator too! :)

**Comment by Rosalie241** [comment]
You can already set game covers, select View -> grid, then right click an item and click 'Set Cover'!

**Comment by Rosalie241** [comment]
I'm going to close the issue due to having answered your main question! If you have any more questions, feel free to open another issue :heart:
