### ISSUE TITLE
Include paraLLEl-RDP and RSP

### ISSUE THREAD

**Issue by anonymous7002** [Rosalie241/RMG#14]

**Comment by sprockkets** [comment]
These are tied to Retroarch, and really, why would you want them since they are not used with why this emulator exists in the first place, using high res textures from Nerrel?

**Comment by Rosalie241** [comment]
> These are tied to Retroarch, and really, why would you want them since they are not used with why this emulator exists in the first place, using high res textures from Nerrel?

They're not tied to retroarch but the parallel plugins *will* be included with RMG eventually, though it'll never be the default plugins.

**Comment by Rosalie241** [comment]
Included in the latest release :heart:: https://github.com/Rosalie241/RMG/releases/latest
