### ISSUE TITLE
RMG installed from AUR crashes if I try to use Dynamic Recompilation (aarch64)

### ISSUE THREAD

**Issue by CCF100** [Rosalie241/RMG#141]
Hi! I installed RMG via the rmg-git package in the AUR, and whenever I try to start a game with Dynamic Recompilation enabled, the emulator gets to the point where it initializes the Dynarec, hangs, and then segfaults. I'm not sure how to troubleshoot this...

**Comment by CCF100** [comment]
After further experimentation, I have discovered that version 0.4.0  (commit 66703970b60f6d5fb4ec5bd39cd892439ea88d65) works fine... So this issue is a regression

**Comment by Rosalie241** [comment]
Can you test v0.4.1?

**Comment by Rosalie241** [comment]
And if v0.4.1 doesn't work, can you try https://github.com/Rosalie241/RMG/commit/5b61f811dabae97f86508ef4fc4d91643c0b1589, and if that commit works, can you see if https://github.com/Rosalie241/RMG/commit/fb12f6432b851704c6e587651bdaacc914adca7a works? I suspect https://github.com/Rosalie241/RMG/commit/fb12f6432b851704c6e587651bdaacc914adca7a must've broken it somehow then.

**Comment by CCF100** [comment]
I'll try the latest commit first, and then report back.

**Comment by CCF100** [comment]
Latest commit still segfaults, trying the other commits...

**Comment by CCF100** [comment]
66703970b60f6d5fb4ec5bd39cd892439ea88d65: Dynarec works
5b61f811dabae97f86508ef4fc4d91643c0b1589: Dynarec works
fb12f6432b851704c6e587651bdaacc914adca7a: Dynarec segfaults
1e6c9063007791bd6651e372fe13f394ed292ab6: Dynarec segfaults
