### ISSUE TITLE
ROM presentation in GUI

### ISSUE THREAD

**Issue by MarcyBesky** [Rosalie241/RMG#145]
Your frontend is progressing very well. Would you mind changing the way ROMs are presented, e.g. like it is done in DuckStation?

At least Title (short version with region), Size and Region as a real flag (maybe Compatibility) would be very nice.

Oh and Dark Mode would be nice as well.

![Example](https://github.com/Rosalie241/RMG/assets/139846289/a2e84fb0-4dad-417b-884e-fb482b7d6fbb)

**Comment by Rosalie241** [comment]
> Your frontend is progressing very well. Would you mind changing the way ROMs are presented, e.g. like it is done in DuckStation?

I like it how it is at the moment so I don't think any change is needed.

> At least Title (short version with region)

That isn't doable at all with the data I have in the existing mupen64plus database.

> Size and Region as a real flag (maybe Compatibility) would be very nice.

I don't really like the flag in pcsx2 so I'd rather have it stay the way it is, and compatability is also something I don't have data for.

> Oh and Dark Mode would be nice as well.

There is one, go to settings -> misc tab -> select 'Fusion Dark' as theme and re-open RMG.

**Comment by MarcyBesky** [comment]
Ok, I forgot that I asked the same question before. What a pity regarding the flag symbol! I like it and I am sure a lot of other guys as well, but it looks like you prefer to make RMG the way you like it instead of asking the RMG users. Nevermind, it's up to you! Nevertheless, thanks for RMG
