### ISSUE TITLE
Open Rom in launch arguments? Does this work?

### ISSUE THREAD

**Issue by lolcatplays** [Rosalie241/RMG#15]

**Comment by Rosalie241** [comment]
Not yet, no, will be added eventually though!

**Comment by lolcatplays** [comment]
Thanks for the reply, no rush

**Comment by Rosalie241** [comment]
I think https://github.com/Rosalie241/RMG/commit/4f8ede0b5eb966fe0b3dc6f4946fdb0b6ca911bc should work fine?

You can download that build here: https://github.com/Rosalie241/RMG/actions/runs/1351616370

Please try that build and tell me if it behaves like you want it to!

**Comment by lolcatplays** [comment]
I'll try it in a bit and let you know my findings

**Comment by lolcatplays** [comment]
> 
> 
> > is it possible to make a toggle to go to fullscreen when a game is launched?
> 
> Hmm, I'll take a look at adding that tomorrow.

cheers :)

**Comment by Rosalie241** [comment]
implemented in https://github.com/Rosalie241/RMG/commit/26005b2a81b54769072392bc9c3c0275d16a0f71, will be included in the next release.

**Comment by lolcatplays** [comment]
Great thanks

**Comment by twyzeas** [comment]
> Just one more thing, is it possible to make a toggle to go to fullscreen when a game is launched?

If anyone's still wondering, you can add the -f parameter for fullscreen
