### ISSUE TITLE
v0.4.5

### ISSUE THREAD

**Issue by hohonadie** [Rosalie241/RMG#150]
hi in RMG v0.4.5 detect this
https://www.virustotal.com/gui/file/7d116266063879d8bdc8b5ed52638a0a1ae2bb2ab31b1991cebc5319d4477f40?nocache=1

before in v0.4.1 virustotal no detect nothing

**Comment by Rosalie241** [comment]
See https://github.com/Rosalie241/RMG/issues/103#issuecomment-1430339326
