### ISSUE TITLE
D-PAD is not defined on Generic USB Joystick (Vendor: 0079 Product: 0006)

### ISSUE THREAD

**Issue by nikusernik** [Rosalie241/RMG#152]
![image](https://github.com/Rosalie241/RMG/assets/17692012/264e9bb0-b027-4aba-8cbe-716337a21269)
D-PAD is not defined on Generic USB Joystick (Vendor: 0079 Product: 0006)

![image](https://github.com/Rosalie241/RMG/assets/17692012/437ce2e6-0948-402c-9ec2-df93d00b73ba)
I do not know how to show the layout correctly. Therefore, I will show it with Simple 64.

**Comment by Rosalie241** [comment]
Thank you a lot for posting the screenshots, they were very helpful!

I don't own a controller which uses a 'joystick hat', but I've tried to implement it, could you try the following build when you have time and tell me if it works for you?:

https://github.com/Rosalie241/RMG/actions/runs/5708063673

**Comment by nikusernik** [comment]
![image](https://github.com/Rosalie241/RMG/assets/17692012/208d5a1d-3c18-41f5-8b94-6926e20e82f1)
It worked. Thanks)

**Comment by Rosalie241** [comment]
it'll be included in the next release of RMG, thank you for testing!
