### ISSUE TITLE
Found out about some viruses that came with your emulator

### ISSUE THREAD

**Issue by DMXrated01** [Rosalie241/RMG#153]
Cutting to the chase to start, I found this website called VirusTotal, and diagnosed both Windows 64 downloads on it, along with three unrelated files.  The two RMGP downloads were the only ones to turn up a virus, and a different one each.

What led me there in the first place was, suffice to say, a virus that I spent a whole week dealing with after experimenting with different emulators for the best emulation possible of this Japanese game called Getter Love!!  This virus started off by redirecting some of my Google searches to Bing, but days later, began to shut my computer off automatically whenever I'd leave it idle for a full half-hour.  I had to reinstall Windows, and decided afterwards to fire up my old computer, which was where I discovered VT to examine your downloads with.

You might want to examine your downloads and look into removing the viruses that I found them to contain.  For convenience, here is VT to examine them with:

https://www.virustotal.com/gui/home/upload

**Comment by Rosalie241** [comment]
See https://github.com/Rosalie241/RMG/issues/103#issuecomment-1430339326, and you probably got a virus from some different software, not RMG.
