### ISSUE TITLE
Two Concerns regarding the "Toggle Vsync" Hotkey.

### ISSUE THREAD

**Issue by JHGT98** [Rosalie241/RMG#155]
Hello, I would like to communicate two matters about the "Toggle Vsync" Hotkey (which is configurable by going to the menu bar -> Settings -> Graphics -> Hotkey).

1) Pressing the key to which you have assigned the "Toggle Vsync" Hotkey causes the RMG window to shrink in size considerably (which as a side effect can take you out of immersion, especially if you were in full screen mode).
If I am not mistaken, this behavior should not occur with this shortcut (the window size should not be affected).

2) Enabling or disabling VSync via this shortcut causes an "Enable/Disable vertical sync" message to appear on the screen.
Although this is not a problem per se, I would like to request, if it would not be too much to ask, the possibility to show/hide this OSD message at will (as it is already possible with many others, by going to the menu bar -> Settings -> Graphics -> OSD -> (Under the "Position" item).

Thank you very much and I am sorry for the inconvenience.

**Comment by Rosalie241** [comment]
I looked into it and I cannot solve issue 1, it has to re-create the OpenGL context and does so properly by using the mupen64plus API, which has a side-effect of resetting the resolution, so nothing I can do there.

Regarding issue 2, after a quick look at the code, it seems like it does respect the OSD settings already, see [1] which leads to [2], which eventually runs [3].

I apologize but there's nothing I can really do right now about this.

[1] https://github.com/gonetz/GLideN64/blob/master/src/VI.cpp#L163
[2] https://github.com/gonetz/GLideN64/blob/master/src/GraphicsDrawer.cpp#L1682
[3] https://github.com/gonetz/GLideN64/blob/master/src/GraphicsDrawer.cpp#L1593
