### ISSUE TITLE
ParaLLEl version

### ISSUE THREAD

**Issue by user18081972** [Rosalie241/RMG#157]
Is 0.45 using the most recent version of ParaLLEl plugins, if not when was it last updated?

**Comment by Rosalie241** [comment]
v0.4.6 will have the latest version, and I currently am unable to check when it was exactly updated last because I changed the way I include 3rdparty projects like parallel recently, but v0.4.5 had a slightly older version.

**Comment by Jj0YzL5nvJ** [comment]
https://github.com/Rosalie241/parallel-rdp-standalone/compare/141d253c4a8b8f29afbbc56a7fbf0d351f07680c...2c2226517c4c8929e08ec944654867e26efe0cf5

Based on: Themaister/parallel-rdp-standalone@8da2be35abbbf503a485993c717e4917a1560324 (Feb 13, 2023)
