### ISSUE TITLE
[Feature Request] Sound Controlling Hotkeys.

### ISSUE THREAD

**Issue by sm3b3** [Rosalie241/RMG#161]
Hi, if it would not be too much trouble, I would like to request the following QoL Sound related hotkeys:
1) Mute/Unmute Volume (Toggle). 
2) Raise Volume.
3) Lower Volume.

If they were to be added, I believe that ideally they should be freely configurable.
Thank you very much for your hard work.

**Comment by Rosalie241** [comment]
It's been included in v0.4.8, thank you for testing!
