### ISSUE TITLE
[Feature request] Drag-and-drop ROM support.

### ISSUE THREAD

**Issue by Crewdne** [Rosalie241/RMG#163]
Hi, I would like to request the possibility to drag ROMs to the RMG window.

If no emulation is active, the new file would be loaded silently, but in case another game is already running, dragging a new file would display a prompt asking for confirmation before stopping the current emulation.

I understand seeing this message could be tiring, so adding a checkbox to RMG in the style of "Don't Show This Prompt Again", would be highly appreciated for those who don't want it.

This functionality is not always obvious, but when implemented, it is very welcome.
This is just my humble request. Thank you very much.

**Comment by Rosalie241** [comment]
Added it in https://github.com/Rosalie241/RMG/commit/5fdfbf50d777390fe334c3dd7c84e47fa1eaf49a, please test it with the following build to see if it works for you: https://github.com/Rosalie241/RMG/actions/runs/5825921197

**Comment by Rosalie241** [comment]
It's been included in v0.4.8, thank you for testing!
