### ISSUE TITLE
[Issue] Loading states causes bad sound and crashing.

### ISSUE THREAD

**Issue by McCloud1710** [Rosalie241/RMG#165]
Greetings . I notice that loading States are causing sound distortions and, most of the time, crashing. 

I tried to change plugins but this keep happening. All the games I tested worked fine until I hit the load state button.

I'm running RMG 0.4.9 in W10 and Linux via flatpak, and this issue happens in both systems.

**Comment by Rosalie241** [comment]
Fixed in v0.5.0, sorry that there have been so many issues since v0.4.8 but hopefully they've all been fixed now!
