### ISSUE TITLE
The world needs an AppImage that simply plays N64 Roms...

### ISSUE THREAD

**Issue by Higherselfhiphop** [Rosalie241/RMG#167]
Hey yall, 
Thanks for your work and time...
I Assume this is only a frontend and not a full Emulation Solution...

Is there a Solution (A Ready to go AppImage) to simply play games...
Or did I miss something?

The world really needs an AppImage N64 Emulatior that just works...
I've been scraping the whole Net and cannot locate, even one AppImage...

Maybe you can kindly assist...

All my gratitude...
Bartman...

**Comment by Rosalie241** [comment]
RMG includes everything by itself, mupen64plus-core, plugins, and the front-end.

**Comment by Higherselfhiphop** [comment]
Thanks for your reply... 
I am working from Debian 11 Bullseye... Linux emulation 
on a Chromebook...
I run this app and get this error...

apply_plugin_settings osal_dynlib_open Failed: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /tmp/.mount_RMG-PoL50Xuz/usr/lib/RMG/Plugin/GFX/mupen64plus-video-GLideN64.so)

Thanks again... I will cherish this AppImage if it works on other Distro projects ahead...

**Comment by Jj0YzL5nvJ** [comment]
Bullseye's uses GCC 10... you need GCC 11 or higher.

**Comment by JakobDev** [comment]
I recommend you to[ setup Flatpak on Chrome OS](https://flathub.org/setup/Chrome%20OS) and install [RMG from Flathub](https://flathub.org/apps/com.github.Rosalie241.RMG). This will work better than the AppImage.
