### ISSUE TITLE
Game Input Settings doesn't save Controller Pak option

### ISSUE THREAD

**Issue by MightyKombat** [Rosalie241/RMG#169]
So in RMG you can right click on a game and select "Edit Game Inputs" so you can have specific button inputs for games a well as what controller paks to use. Except that last bit doesn't save. If I set, say, Mystical Ninja to use the Memory pak instead of Rumble, as soon as I exit out of the Input options screen even with the OK button, it always reverts back to the Rumble pak, ignoring what I set. The game thinks there's no memory pak inserted and when I check settings again its just reverted back to the Rumble pak no matter what. I can't tell if its just setting my overall controller inputs or something.

**Comment by Rosalie241** [comment]
I've improved the code that handles the 'Edit Game Input Settings' (see https://github.com/Rosalie241/RMG/commit/1e03d59592519532ebb4a98286541efe4c957304, https://github.com/Rosalie241/RMG/commit/6c66268002da2dfe897313b53fe98e979062031a and https://github.com/Rosalie241/RMG/commit/45cb32b4290ff5f5894d38e512354a4faab18007), please try the following CI build when it's done building (in about 15 minutes or so): https://github.com/Rosalie241/RMG/actions/runs/5986622724

**Comment by MightyKombat** [comment]
That's fixed it, thanks.

**Comment by Rosalie241** [comment]
The fix has been included in v0.5.1, thank you for the report!
