### ISSUE TITLE
[Bug] Parallel RDP doesn't work with VRR/Freesync and non-60hz screen

### ISSUE THREAD

**Issue by Immersion95** [Rosalie241/RMG#194]
I know there is an issue with GL/Vulkan (same as Ares/Simple 64) but there is no way to have a smooth experience with Parallel RDP and any non 60hz screen.

VRR/Freesync doesn't trigger, thus having uneven frametime.  Angrylion RDP plus works flawlessly in that regards.

**Comment by Calinou** [comment]
Which OS and graphics card are you using? If on Windows, is your GPU configured to use VRR for fullscreen applications only, or both windowed and fullscreen? On NVIDIA, you can adjust this in the NVIDIA Control Panel.

**Comment by Immersion95** [comment]
Hi, I'm using AMD/Adrenaline with single monitor. Win 11 + 7800 XT. I forced it in Adrenaline to no avail.

**Comment by Immersion95** [comment]
Solved :)

**Comment by Immersion95** [comment]
Tips : Don't use "Synchronize audio" as the framerate stutters a lot with VRR/Vsync Off.

In audio --> Decrease "Primary buffer size" to 1 to not have any audio delay
