### ISSUE TITLE
HiDPI Video Output Issue

### ISSUE THREAD

**Issue by flagrama** [Rosalie241/RMG#2]
Video does not fill full window when using HiDPI settings. Screenshot of current display configuration provided.

![image](https://user-images.githubusercontent.com/634079/100165287-e4dbba00-2e87-11eb-9364-78c05cce79db.png)
![image](https://user-images.githubusercontent.com/634079/100165336-03da4c00-2e88-11eb-81e0-0c0c1e89b9f9.png)

**Comment by Rosalie241** [comment]
should be fixed with https://github.com/Rosalie241/RMG/commit/20a59aa2a37fc8353d99974d27b18a694e8dc988

**Comment by flagrama** [comment]
Looks good, thanks!
![image](https://user-images.githubusercontent.com/634079/100254159-f49ee100-2f0f-11eb-82f1-a27d005f8af8.png)
