### ISSUE TITLE
Navigating the UI with a screen reader

### ISSUE THREAD

**Issue by Gamulation** [Rosalie241/RMG#20]
Hi
I have tried this out and this is really good, it has the settings I want and I can use it very well.
sometimes whenever I press ok to exit settings I can't get back in. I'm using the keyboard to navigate around and there for use the alt menu. When going to options sometimes my screen reader doesn't speak anything.
A screen reader is a software for blind people that let's them navigate a computer. This never happens the first time the app is opened. I would love for this to get fixed. Thanks for reading.

**Comment by Rosalie241** [comment]
I'm not sure how to help here, I don't know how screenreaders work sadly and I don't think I can control them.
