### ISSUE TITLE
Azimer RSP not loading

### ISSUE THREAD

**Issue by Soapsuds** [Rosalie241/RMG#213]
Hey there, 

System Info: 
RMG v0.5.5
I've installed via Flatpak on Archlinux.

Plugin Page: 
![image](https://github.com/Rosalie241/RMG/assets/3620789/a64def28-0053-411a-bded-9844e336dc8d)

But checking the log ParaLLEl RSP gets loaded instead:
![image](https://github.com/Rosalie241/RMG/assets/3620789/1fac7c7e-cfe1-4124-b541-eb59c1e4fe20)

I'm honestly not sure what the differences there are between the two, but I think I read Azimer is the default.

**Comment by Rosalie241** [comment]
parallel-rsp is set as the fallback for azimer rsp, so if a game uses an opcode that azimer hasn't implemented, it'll use parallel-rsp for that opcode instead.

so azimer does load successfully but jut uses parallel rsp as fallback, which is intended.
