### ISSUE TITLE
RMG Updater Error - "CoreUnzip() Failed!"

### ISSUE THREAD

**Issue by danielah05** [Rosalie241/RMG#229]
when trying to update, it installs the latest update but then gives a "CoreUnzip() Failed!" error.
it seems like it successfully downloads the update, but just like the error says, the unzipping part is failing for some reason.
![RMG_dbl5cLMxxT](https://github.com/Rosalie241/RMG/assets/35849198/02bbb573-f5cb-43ff-a166-2825dfe854d6)
![explorer_4TaSSwF686](https://github.com/Rosalie241/RMG/assets/35849198/ae1d9595-7267-4ec9-b696-26752940fb35)
![explorer_NWKWPCscIF](https://github.com/Rosalie241/RMG/assets/35849198/0ab2193c-d457-414e-87a1-6dc41c45a2e0)

in case you need to know this, i am currently running "Windows 10 Pro 22H2"

i can just manually extract the update from the zip just fine btw, but it would be nice if the updater just worked properly

**Comment by Rosalie241** [comment]
should've been fixed in v0.5.6 already, what version are you trying to update from?

**Comment by danielah05** [comment]
oh oops, i think i was one version behind v0.5.6 then, yeah the auto updating works on that one and after, my mistake!
