### ISSUE TITLE
In-app update from 0.5.2 to 0.5.7 (Win64, Portable) fails

### ISSUE THREAD

**Issue by LaundryHamper** [Rosalie241/RMG#232]
"CoreUnzip: failed to open file!C:\Users\Ol\AppData\Local\Temp\Rosalie's Mupen GUI-bGntPQ/extract/Core/mupen64plus.dll"

The zip does download to the temp directory and extracting using 7zip completes without error.

Apologies if this is already fixed, I do see a recent commit regarding CoreUnzip

**Comment by Rosalie241** [comment]
this was fixed in v0.5.6, update manually to that and then it'll update fine.
