### ISSUE TITLE
Mupen64plus raphnetraw Input Plugin not working under Linux

### ISSUE THREAD

**Issue by duleell** [Rosalie241/RMG#247]
RMG version: 0.5.8, AppImage
OS: Linux (Ubuntu 23.10, 6.5.0-27-generic)
Input Plugin: Mupen64plus raphnetraw Input Plugin

Problem:
Start a ROM to emulate, then it says "NO CONTROLLER - There are no Controllers connected"  

PS:
Mupen64plus raphnetraw Input Plugin works perfectly with RMG v0.5.8 under Windows, even rumble works correctly.

**Comment by Rosalie241** [comment]
Try installing this udev rule: https://github.com/raphnet/gcn64tools/blob/master/scripts/10-raphnet.rules

**Comment by duleell** [comment]
> Try installing this udev rule: https://github.com/raphnet/gcn64tools/blob/master/scripts/10-raphnet.rules

Aha, it just works! Thank you buddy!

"""
Under Linux, you should configure udev to give the proper permissions to your user, otherwise communicating with the device won't be possible. The same requirement also applies to dfu-programmer.

An easy way to do this is to copy the two files below to /etc/udev/rules.d, restart udev and reconnect the devices.

scripts/10-atmel-dfu.rules scripts/10-raphnet.rules
"""

LOL, gcn64ctl_gui and RMG work perfectly, and don't need root permission now!
