### ISSUE TITLE
RMG crashing using the AppImage version when i launch games using ParaLLel

### ISSUE THREAD

**Issue by dCo3lh0** [Rosalie241/RMG#249]
I've tried already using the Flatpak and AppImage, i normally use the AppImage version in the past, i can use the Flatpak as well without issues, anyways, I've tried using the AppImages using the ParaLLel video plugin and it crashes the application when launching the game, it instantly gives me Segmentation fault, don't know whats wrong, but that's that.

**Comment by Rosalie241** [comment]
This is an issue that AppImages can have on certain distros, and there's nothing I can do, it works fine for me on Fedora 40.
