### ISSUE TITLE
Arm64 RaspberryPi5 compiles fine, video is blank, sound works

### ISSUE THREAD

**Issue by StarPlayrX** [Rosalie241/RMG#250]
RaspberryPi5 8Gb RAM, 64Gb SD Samsung Evo Select, running Ubuntu 23.10, compiled RMG from source. Sound works with Mario Kart (get welcome to Mario Kart), but the video is black. 

This is when the kernel level KMS V3D driver is on. If I turn it off and reboot, I get video but obviously notacceleration. 

Ubuntu, my Pi5 supports OpenGL 3.1 and Vulkan 1.1.

Tried all three plugins and all are blank.

Will try again later.

**Comment by Rosalie241** [comment]
GLideN64 and angrylion-rdp-plus require OpenGL 3.3, you might be able to fake support for that with an environment variable, which works on my pinebook pro, but I don't have a raspberry pi 5 to test it with.

**Comment by StarPlayrX** [comment]
Ok. I will look into that. I have OpenGL 3.1 How do I set the env variable? On Apr 23, 2024, at 10:55 AM, Rosalie ***@***.***> wrote:﻿
GLideN64 and angrylion-rdp-plus require OpenGL 3.3, you might be able to fake support for that with an environment variable, which works on my pinebook pro, but I don't have a raspberry pi 5 to test it with.

**Comment by Rosalie241** [comment]
I use `MESA_GL_VERSION_OVERRIDE=3.3` on my pinebook pro

**Comment by StarPlayrX** [comment]
I decided to compile Dolphin on Pi 5 expecting it to fail miserably. And loaded Mortal Kombat, 1.5Gb .iso with a Samsung Evo Select SD card (not an SSD or NVMe). By all accounts this should not work. Game Cube games are considered serious hardware and a Pi5 is not even close. 

To my surprise, MK loaded right up and the screen shows V3D three times in yellow recognizing the hardware driver. The intro movie and sound all are working, not stuttering, sound not stuttering. I have not had time yet to play any games, but the fight demo works. 

Main reason I expected this not to work is arcade games like Midway's NFL Blitz on MAME is unplayable on the Pi5. And I expected games running on Dolphin to do the same.  

Let me know if you want any hardware to test RMG with. I may further my research here and try to get the Sega/Tri build to compile and see if I can get Mario Kart GP1 and GP2 arcade to play on the a special Dolphin build.

**Comment by Rosalie241** [comment]
After investigating further, I've implemented an OpenGL ES option, can you try compiling the latest master and seeing if it works correctly for you now? It's in settings -> emulation -> 'OpenGL Type' and it should be 'OpenGL ES' on arm/arm64 already by default.

and apologies for taking so long to take a closer look.

**Comment by StarPlayrX** [comment]
Thank you for taking a second look at it. I will definitely give it a whirl and report back.
