### ISSUE TITLE
Black lines in the textures

### ISSUE THREAD

**Issue by reignerdeustcher** [Rosalie241/RMG#252]
I have this issue in all games: 

![turok_dinosaur_hunte-000](https://github.com/Rosalie241/RMG/assets/79814905/5407dae2-6455-4a2c-b51f-710f0a1736d6)

**Comment by Rosalie241** [comment]
Can you try enabling 'inaccurate texture coordinates' in the graphics settings?

**Comment by reignerdeustcher** [comment]
> Can you try enabling 'inaccurate texture coordinates' in the graphics settings?

oh that fix it thanks, i solved it disabling brz textures
