### ISSUE TITLE
Imported State Save has no working Audio

### ISSUE THREAD

**Issue by LaCaptainSources** [Rosalie241/RMG#262]
-- Audio not loading.

I have a state save from another emulator, which has complete compatibility with the emulator. The main problem is, when i load that state all the audio of the game dissapears. No matter what i do, it never returns.

**Comment by arcastro** [comment]
Hi, I'm having this same issue when loading a save-state from pj64 (pj.zip).

Any reason this issue was closed? Any insight into the cause or work needed to fix?
