### ISSUE TITLE
Quest64 has staticy glitchy border around it

### ISSUE THREAD

**Issue by zlice** [Rosalie241/RMG#264]
0.5.9 is fine

![border](https://github.com/Rosalie241/RMG/assets/8009811/07beee91-79d3-4f24-a28a-916dcb8205fc)

**Comment by Rosalie241** [comment]
Quitting RMG and starting it again should fix that

**Comment by zlice** [comment]
Didn't change for me

**Comment by zlice** [comment]
so maybe a linux issue...or worse, intel gpu issue.

linux 6.9
a770
mesa 24.1.0

**Comment by CCCP1982** [comment]
> so maybe a linux issue...or worse, intel gpu issue.
> 
> linux 6.9 a770 mesa 24.1.0

Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz   3.60 GHz
12,0 ГБ
Nvidia GT 8500 512MB DDR2
))

**Comment by zlice** [comment]
deleted my `~/.config/RMG` and re-ran. things are fine. not sure what it was but clearly a settings issue
