### ISSUE TITLE
Full screen 4:3 vertical sync is not enabled

### ISSUE THREAD

**Issue by CCCP1982** [Rosalie241/RMG#266]
[RMG](https://github.com/Rosalie241/RMG) 0.6.0

**Plugin - mupen64plus-video-angrylion-plus.dll**

![Снимок экрана (491)](https://github.com/Rosalie241/RMG/assets/142115581/a00108b0-ca0d-401c-a250-f6166a1c3b0a)

https://github.com/Rosalie241/RMG/assets/142115581/72a26f58-4609-460b-9388-a758474c697a

**Comment by Jj0YzL5nvJ** [comment]
Try:
`Compatibility > Slow`
`Threads > 4`

Note: Don't use all your threads (`0`) unless your CPU has 4 or less, maximum use 2/3 or 3/4 of all your threads.

**Comment by Rosalie241** [comment]
That's a nice catch, thanks for reporting it, I've added the missing vsync option to angrylion-rdp-plus!

Can you try the following build to see if that works for you: https://github.com/Rosalie241/RMG/actions/runs/9346288222

If that works for you then I can include it in the next release :heart:

**Comment by CCCP1982** [comment]
> That's a nice catch, thanks for reporting it, I've added the missing vsync option to angrylion-rdp-plus!
> 
> Can you try the following build to see if that works for you: https://github.com/Rosalie241/RMG/actions/runs/9346288222
> 
> If that works for you then I can include it in the next release ❤️

Yes it works fine thank you for your efforts

**Comment by Rosalie241** [comment]
It's been added in v0.6.1, thanks for reporting it :heart:
