### ISSUE TITLE
Missing some nice additions to RMG ...

### ISSUE THREAD

**Issue by MarcyBesky** [Rosalie241/RMG#277]
Hi Rosalie,

RMG is a nice piece of software. I use it on a regualar basis. I wished that some fancy gimmicks would be included, like real colorful flags for the region of a rom.

Don't you agree, that this would make RMG more attractive?

Thanks

**Comment by Rosalie241** [comment]
You've already opened an issue about this before and my response is the same, see https://github.com/Rosalie241/RMG/issues/145#issuecomment-1639724135
