### ISSUE TITLE
Pokémon Snap: Oak's Mark is fixed, but now Pokémon are mislabeled

### ISSUE THREAD

**Issue by MattysMasquerades** [Rosalie241/RMG#278]
![Screenshot (6120)](https://github.com/Rosalie241/RMG/assets/174567102/02c0400f-655c-4e16-8280-2d945aeb843f)

Settings -> Plugins -> ParaLLel RSP as the Reality Signal Processor Plugin and parallel as the Video Plugin

Oak's mark is working just fine now! I will continue playing!

**Comment by MattysMasquerades** [comment]
As I continue playing, I notice some Pokémon are mislabeled, and upon development some of them stay and others... get things like this.
![Screenshot (6122)](https://github.com/Rosalie241/RMG/assets/174567102/5911047f-c239-4548-b09f-f567bd5a04ee)
![Screenshot (6124)](https://github.com/Rosalie241/RMG/assets/174567102/8674df62-2198-49a7-bacb-c187f72b6526)
![Screenshot (6126)](https://github.com/Rosalie241/RMG/assets/174567102/67872f49-ab21-422e-8e64-8e73c7355885)
![Screenshot (6127)](https://github.com/Rosalie241/RMG/assets/174567102/9b630c51-4475-4783-a9fb-d37879075f23)

**Comment by MattysMasquerades** [comment]
![Screenshot (6132)](https://github.com/Rosalie241/RMG/assets/174567102/3f2ae166-954b-4c0b-aa76-f921b788d315)

This combo seems to work.

**Comment by inukaze** [comment]
i can't mark pictures for Oak neither USA version neither Spain version, the Button is just disabled
My pc is old, and i can't use Vulkan. 

I try to set core to pure interpreter, rsp in the 3 options, and the unique graphical plugin works for me is GlideN64, but the thing is i can't use "Mark Oak" 

Spain Version : ![Image](https://github.com/user-attachments/assets/cb1a7d66-e65a-4d7b-bfb3-846d96e407d2)

USA Version : ![Image](https://github.com/user-attachments/assets/c2d8ea7f-e997-49f7-a746-1478f5c34201)
