### ISSUE TITLE
[REQUEST] CRT shader

### ISSUE THREAD

**Issue by rrrcabral** [Rosalie241/RMG#282]
The Parallel Plugin at 1x is very accurate, but the pixels are very blocky/square, to recreate the feeling of the 90s perfectly all you need to do is apply a CRT filter over it, to soften these "square pixels".
In retroarch there are these filters, and for Rosalie to be perfect for me that's all that was missing.

**Comment by Rosalie241** [comment]
Use reshade if you desire that, I have no plans to add shader support to RMG.
