### ISSUE TITLE
[Feature Request] Mupen FZ Save Compatibility

### ISSUE THREAD

**Issue by aurokin** [Rosalie241/RMG#283]
Mupen FZ on android saves savedata with the following filename "Legend of Zelda, The - Ocarina of Time (U) (V1.0) [!].sra" (which does not match my filename) - is it possible to add compatibility for this format in RMG?

Emulator in question: https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita&hl=en_US

**Comment by Rosalie241** [comment]
Those saves should work as-is without changing the filename

**Comment by aurokin** [comment]
Is it possible for rmg to create save files in this format for compatibility the other way?

**Comment by Rosalie241** [comment]
No
