### ISSUE TITLE
Some Features requests

### ISSUE THREAD

**Issue by ha7ak3** [Rosalie241/RMG#29]
Hi, Rosalie
I have some features ideas in mind that maybe you can implement someday if you think that it's possible
You can add them to the very bottom of your todo list if you want.

- Grid mode for the rom browser with an option to set a custom thumbnail.
- A way to set a custom controller profile per game.
- Auto center the main and game windows to the screen.

Greetings

**Comment by RadikAlice** [comment]
Well, despite lack of comments. So far two out of three have been implemented
Saw this and decided to let you know. Also kinda just wanted to gush about it
Even by now, everyone's done such a good job it should be recommended over M64Py. Like officially

**Comment by ha7ak3** [comment]
Yeah Rosalie has done a lot of progress so I'm closing this.
