### ISSUE TITLE
[Request] Add an option for setting null inputs on the Mayflash Adapter input plugin config file.

### ISSUE THREAD

**Issue by retrobenny** [Rosalie241/RMG#290]
It gets really frustrating when I accidentally hit C-Stick Left or Right when trying to quickly use it for C-Up and C-Down so it would helpful if I could set those to "null" to effectively disable them to avoid the high chance of playing the wrong ocarina/instrument notes or using the wrong item (wasting bombs/bombchus) or action in various games without intention.

It doesn't help that the config stubbornly deletes all changes and reverts to defaults if you have anything invalid, so I can't just put invalid buttons to avoid the issue as a dirty solution.

**Comment by GhostlyDark** [comment]
Rust does not like `null` as a value, so I chose `None`.
I tried the changes in my own launcher and it worked. Setting a button to `None` effectively disables it (sends 0x0000, which does nothing as you'd expect).

**Comment by retrobenny** [comment]
Awesome, thank you kindly!
