### ISSUE TITLE
"Open with" Broken

### ISSUE THREAD

**Issue by poudink** [Rosalie241/RMG#30]
Trying to launch a ROM through the open with option/setting RMG as the default application for N64 ROMs doesn't work. RMG will be opened, but the ROM will not be launched. Not sure if this is a bug or simply an unimplemented feature. In case it's the former, I'm using Fedora Linux (KDE) and have RMG installed using Flatpak.

**Comment by Rosalie241** [comment]
Does changing `Exec=RMG` to `Exec=RMG %f` in the `.desktop` file fix it?

**Comment by poudink** [comment]
the .deskop file has "Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=RMG com.github.Rosalie241.RMG", actually. taking on %f at the end doesn't do anything.

**Comment by Rosalie241** [comment]
Oh, right, it's flatpak, I'll try it locally soon:tm: and see if that fixes it

**Comment by Rosalie241** [comment]
Fixed with https://github.com/Rosalie241/RMG/commit/0a63c035a97912e01153889387ca8b62321b4764, will be included in the next release
