### ISSUE TITLE
Is this malware? or for real?

### ISSUE THREAD

**Issue by Philgamerk98** [Rosalie241/RMG#307]
I never heard of this before since I hardly used Mupen but had no idea that the original Mupen only works for 32 bit Windows and this one strangely works with 64 bit windows! I was just wondering if this was made by a legit author since when I installed it, I noticed my pc was losing disk space slowly going down itself! I tried cleaning up the cache and deleting the crap it dumps when I rip a model with it on a new folder for deleting and even after I uninstalled it my disk space is still the same! Whats going on? or is there another place in the emulator I haven't look at to clean up? Tell me what I should do. Im using this as a alternative to avoid waiting through 30 seconds with Project 64's ridiculous waiting screen and this emulator works with the only plugin I could ever find for ripping 64DD models! Just tell me if this emulator isn't something bad for my pc or at least please look into it and see what needs to be cleaned besides the cache. I also noticed my rom log had a list of games I don't remember playing this emulator with! The list shows Yoshi Story, Goldeneye, I never played these games on my emulator! Thought it might be worth to bring it up here.

**Comment by GhostlyDark** [comment]
Mupen64Plus does work on 64-bit Windows since many years and yes, this is a legit frontend for the mupen64plus project - which by itself, doesn't ship with a frontend.

I made a launcher that also runs mupen64plus 64-bit:
https://github.com/GhostlyDark/EMG

And here's a fork of PJ64 without the stupid nag screen:
https://github.com/GhostlyDark/project64/releases

Aside from the main folder, the only other place it likely stores files is `%appdata%/RMG`.
RMG shouldn't be responsible to waste your disk space any other way.

**Comment by Rosalie241** [comment]
I'm sorry I didn't reply earlier, but yes, what GhostlyDark said is incorrect, RMG shouldn't secretly take up a lot of disk space!

I will mention there was an issue a while ago with GLideN64 putting its errors in a big log file, but I've fixed that in v0.6.0 already so maybe try updating to the latest version?

There's not much more I can add to this so if there are further issues, let me know!

**Comment by Jj0YzL5nvJ** [comment]
To me it sounds more like a "_ghost index_" (_I don't know the official name_) on NTFS after auto-fixing a dead sector on an SSD (_**thx [TRIM](https://en.wikipedia.org/wiki/Trim_(computing)) /s**_). One of the symptoms is a discrepancy between the calculation of remaining disk capacity displayed between "_This PC_" and "_Storage Space_" from the AppX interface.
When you try to trace the source using "properties", you may find a directory that takes up a lot of disk space, but its contents are much smaller. You can try to fix it with `chkdsk c: /f /r`... and consider buying a new replacement disk. SSDs don't last long anyway, use HDDs to store what's really important.
