### ISSUE TITLE
[REQUEST] Add support for multiple inputs

### ISSUE THREAD

**Issue by Kilicool64** [Rosalie241/RMG#308]
From what I can gather, there appears to be no way to map multiple inputs to the same part of the N64 controller.

This is inconvenient for me. I'm used to playing with both my controller's left analog stick and its D-pad mapped to the N64's analog stick. It can be useful in Paper Mario, which doesn't use the d-pad at all and sometimes tasks you with repeatedly flicking the analog stick to the left. Doing that with a D-pad is probably better for the health of both my fingers and my analog stick. So I'd appreciate if this could be supported here.

**Comment by Rosalie241** [comment]
You can do that, press the + button next to a mapping and press the controller button of your choice, then you'll have multiple controller inputs bound to the same n64 input.

**Comment by Kilicool64** [comment]
Okay, that actually worked. For some reason, the + button malfunctioned the first time I tried to configure my controller and just overwrote my first mapped input. It worked fine this time. So I guess this is resolved, but there might still be a bug somewhere in the UI.

**Comment by bemug** [comment]
I was wondering the same and did not understand what the '+'  was for. Thanks both of you for opening this issue and answering it.

**Comment by bemug** [comment]
For the record if you try to add the same input as the already bound input with the '+' it does nothing, which is logical.
I think I was fooled for this reason. It could be why you think it malfunctioned the first time @Kilicool64.

**Comment by Kilicool64** [comment]
If my memory doesn't fail me, the way it played out for me was that I first mapped moving my analog stick up to moving the N64 analog stick up. Then I clicked the plus button and pressed up on my D-pad. But that just overwrote my previous mapping instead of being added to it. So I falsely concluded the button was useless.
