### ISSUE TITLE
SCANNING THE GAME FOLDER ! 

### ISSUE THREAD

**Issue by CCCP1982** [Rosalie241/RMG#309]
It does not scan or filter the folder and letters correctly.

![Снимок экрана (372)](https://github.com/user-attachments/assets/650b1e50-e088-415f-a1df-6740fe8a523a)

**Comment by Rosalie241** [comment]
By default RMG is limited to finding 250 ROMs, you can change this limit in settings -> rombrowser -> change the search limit.

I should change this limit, I'll try to increase the limit for the next release.

**Comment by CCCP1982** [comment]
> By default RMG is limited to finding 250 ROMs, you can change this limit in settings -> rombrowser -> change the search limit.
> 
> I should change this limit, I'll try to increase the limit for the next release.

СПАСИБО!!!!

**Comment by Rosalie241** [comment]
The default has been changed in v0.6.9, so I'll close the issue now!
