### ISSUE TITLE
Tip Toe Banjo Tooie 

### ISSUE THREAD

**Issue by fastrizwaan** [Rosalie241/RMG#4]
https://www.youtube.com/watch?v=C3cERIA8S0E , please see the description, using SDL I could get Banjo to tip toe, but input plugin in RMG does not allow Tip Toe.

Project64 has N-Rage Input plugin which allows Analog Stick Range we can set it to 15-20% and we can do tip toe easily.

![Screenshot from 2020-12-28 23-37-24](https://user-images.githubusercontent.com/1161682/103234426-aa24e000-4965-11eb-8846-83890f290af1.png)

**Comment by Rosalie241** [comment]
I'd need to modify the input plugin, right now I just took Logan's input plugin and my plan is to eventually write my own.

**Comment by fastrizwaan** [comment]
great!
