### ISSUE TITLE
Cannot Change Fullscreen Resolution. 

### ISSUE THREAD

**Issue by link444112** [Rosalie241/RMG#41]
I can't seem to change the resolution for fullscreen mode, on Windows 11 machine. I don't remember having this issue with Linux Flatpak version. Editing the GFX plugin cfg simply reverts on RMG startup. Thank you! 
![Screenshot 2022-05-14 135406](https://user-images.githubusercontent.com/104740380/168443179-d1e3f0cd-ee26-4139-9156-aa715abc3846.png)

**Comment by Xii-Nyth** [comment]
Is the file set to read only? Ive never had such an issue with glide

**Comment by Rosalie241** [comment]
This is intended behavior.
