### ISSUE TITLE
Texture packs will only load from cache?

### ISSUE THREAD

**Issue by Xii-Nyth** [Rosalie241/RMG#44]
Using the same test files and test cache that worked in 1964 (cache was made in 1964), I can only load up from the cache. Meaning also I cannot generate cache using rmg since the images never load up.

Normally would just go ahead and work on my pack in 1964 then, but rogue squadron does not like 1964 that much unless I use very particular settings on an older version of glide.

**Comment by Xii-Nyth** [comment]
Note that memorycache gets generated fine when setting to store, etc

**Comment by Xii-Nyth** [comment]
These are the 2 steps which are skipped
<img width="800" alt="1964-14-39-21" src="https://user-images.githubusercontent.com/101597311/171724578-5bd27bc7-a626-4763-b996-eeed34e2adbb.png">
<img width="800" alt="1964-14-39-33" src="https://user-images.githubusercontent.com/101597311/171724581-0a7f3918-c11c-46a5-be04-52605f169aaa.png">

**Comment by Rosalie241** [comment]
Should be fixed in v0.3.0!
