### ISSUE TITLE
[Linux] How to downgrade Gliden64 plugin? (Having issues with current version)

### ISSUE THREAD

**Issue by surec-or** [Rosalie241/RMG#47]
Because Project64 inputs weren't working, and I wanted to use MMHD, I decided to use RMG. Unfortunately, I was having issues in-game when it came to certain elements, even without the texture pack. Opening the inventory will just show a black screen without the texture pack, and a weird render rainbow texture with it. Same goes with the lens of truth. Hidden objects show up and the vignette show up, but nothing else does.

I assume this is an issue with the Gliden64 version I'm using, but I have no idea how to change it.

**Comment by Jj0YzL5nvJ** [comment]
Upgrading is a better solution: https://github.com/Rosalie241/RMG/actions/runs/2649002823

And clean your **shader cache**:
```
$ rm -rf ${HOME}/.cache/mupen64plus ${HOME}/.cache/mesa_shader_cache
```

**Comment by surec-or** [comment]
Thanks, that fixed the issue
