### ISSUE TITLE
Feature Request: Option to press ESC to quit RMG

### ISSUE THREAD

**Issue by Andrewpaps** [Rosalie241/RMG#55]
Please add the option to press ESC to quit the program as it is handy for using RMG with emulator front ends. Thanks!

**Comment by GhostlyDark** [comment]
![image](https://user-images.githubusercontent.com/31742919/199850995-2ef3e366-724c-4295-80b0-1c3a650681b0.png)

**Comment by Rosalie241** [comment]
you can change the keybindings in settings -> Hotkeys like what GhostlyDark shows, closing
