### ISSUE TITLE
Some Games Crashing

### ISSUE THREAD

**Issue by Palmsunday** [Rosalie241/RMG#57]
Played Mario 64 without any issues, now playing Castlevania: Legacy of Darkness, playing Cornell's quest, noticed it crashes whenever you pickup "the contract" item throughout the game, and right after the first fight with Dracula (the final boss) the game also crashes, just freezes then the program closes, no idea why. Could this be flatpak related?

**Comment by Rosalie241** [comment]
Does switching to interpreter help? (Settings -> CPU emulator)

**Comment by Palmsunday** [comment]
No, I tried all CPU options.

**Comment by Rosalie241** [comment]
Could you give me a save state of the game? (And a hash of the ROM which you can find in 'rom browser -> right click -> ROM information -> MD5')

**Comment by Palmsunday** [comment]
Ok, this is the European version of Castlevania: Legacy of Darkness.
MD5: 78D5F8A98A5ED21D0817856BCD2AD750

I also noticed while playing the same parts that normally crash on a different emulator I see a semi transparant black box around the screen, could be something graphics related.
[Castlevania.zip](https://github.com/Rosalie241/RMG/files/9992672/Castlevania.zip)

**Comment by Rosalie241** [comment]
I discovered this was a crash inside GLideN64 and it doesn't occur in LLE GFX plugins, so I made an experimental GLideN64 patch, which, when upstreamed, will be released alongside a new RMG version.

For now though, you can try switching to a LLE GFX plugin (i.e parallel, though also make sure you use a LLE RSP plugin aswell, also i.e parallel) which should prevent the crash.

**Comment by Rosalie241** [comment]
Fixed in v0.1.7
