### ISSUE TITLE
Game List Capped to 50 items

### ISSUE THREAD

**Issue by LodanZark** [Rosalie241/RMG#60]
Setting up the ROM Directory only displays the first 50 items (in alphabetic order), not sure if it's a bug or if it's the way the game list was intended to be.

**Comment by Rosalie241** [comment]
This can be changed in the settings, check the user interface tab and then rombrowser.

**Comment by thekovic** [comment]
Good thing I had a look in here. I noticed the default has increased since this issue was first opened (50->250) but even that's not enough if you have the entire N64 library like me :D
