### ISSUE TITLE
[BUG]Fail to launch if the Rom file name contains Chinese/Japanese characters

### ISSUE THREAD

**Issue by ibin7777** [Rosalie241/RMG#61]
If the rom file name contains Chinese or Japanese letters, this file won't be scanned in the rom directory, and will fail to launch if manually open ROM
![image](https://user-images.githubusercontent.com/64576479/202292968-e17f0454-c813-4d5e-97d6-f48a53caaca9.png)
![image](https://user-images.githubusercontent.com/64576479/202293165-0637c05f-5591-40fb-a162-937b07e99e18.png)

**Comment by Rosalie241** [comment]
https://github.com/Rosalie241/RMG/actions/runs/3500238130 should resolve it, it'll be included in the next release

**Comment by Rosalie241** [comment]
v0.1.9 has been released with the fix.
