### ISSUE TITLE
Overclocking factor isn't workign as intended?

### ISSUE THREAD

**Issue by Tasosgemah** [Rosalie241/RMG#65]
I'm not sure if this feature is working properly. Comparing it to the PJ64 equivalent, it doesn't seem so.

I played a lot of Goldeneye and PD in PJ64 using the "overclocking modifier". Combining counter per-op "1" with overclocking to "3", the result is a smooth experience at 60fps with no slowdowns anywhere. And if there is some odd slowdown in PD here and there, it cleans up at overclock to "4". Basically, the higher the modifier number is, the faster the N64 gets. And at 4x it's fast enough to brute force both games at uninterrupted 60fps.

This, however, can't be achieved in this emulator. Using the same settings (counter per Op "1" and overclocking to ""3" or "4") makes the games run at 60fps on average, yes, but they still slowdown a lot in many different areas. One area you can test is the first level, right after the tunnel. This is a part is obviously more demanding but the overclock in PJ64 completely brute forces through it. In this emulator it doesn't, you will get slowdowns to 30fps or less.

In fact, i noticed that after "3", all the higher numbers don't make any difference at all. Even at "11" the result is the exact same as "3". Which apparently isn't enough to make these games run smooth at **all times**.

So i'm not sure if it's a bug, or a lacking implementation or it's working as intended.

**Comment by Rosalie241** [comment]
The counter factor overclock option isn't the same as the one from Project64, from further testing (thanks to @GhostlyDark aswell for testing), it seems that it works like intended, so nothing I can do for now.
