### ISSUE TITLE
RMG crashes when exiting/closing the emulator on Windows

### ISSUE THREAD

**Issue by RokkumanX** [Rosalie241/RMG#68]
**Describe the bug**
After you are done playing something, have stopped the emulation and want to close/exit the emulator it crashes.
It also crashes upon exiting/closing the emulator if you haven't played anything and have just opened the emulator and close afterwards.

**To Reproduce**
1. Open RMG.exe
2. Click on File
3. Click on Exit
4. Crash

**Expected behavior**
Expected behavior would be to exit/close the emulator without crashes.

**Screenshots**
N/A

**Desktop (please complete the following information):**
- OS: Windows 10 Enterprise LTSB 21H2
- GPU: NVIDIA GTX 1070
- CPU: Intel Core i7 8700K
- RAM: 64GB

**Additional context**
According to the built in Reliability monitor in Windows this is what it has to say about the crash of RMG.exe

Problem - Stopped working

Faulting application name: RMG.exe
Faulting module name: mupen64plus.dll_unloaded
Exception code: 0x0000005
Fault offset: 0x0000000000009980
Faulting process id: 0xbf8
Faulting module path: mupen64plus.dll

**Comment by Rosalie241** [comment]
I've tried to debug this multiple times but I have no idea what's going on here sadly, this is a known issue on windows which I've tried to fix multiple times, and ofcourse it works fine on linux where debugging would be much easier.

So I'll try to look into it some more in the future but for now I'd recommend ignoring the crash.

Thank you for the report though :heart:

**Comment by RokkumanX** [comment]
Thanks for taking your time to respond @Rosalie241 

Here's hoping that the issue some day will be fixed ❤️

You are doing a great job and I really like RMG!

**Comment by Rosalie241** [comment]
should be fixed with https://github.com/Rosalie241/RMG/commit/2a346c4cfa6f5f69b5b863dcbb7b3accd1f1ac3c, thank you for the report :heart:

**Comment by RokkumanX** [comment]
Thank you very much!
