### ISSUE TITLE
Error On Steam Deck Since last update

### ISSUE THREAD

**Issue by Gilipheoun** [Rosalie241/RMG#69]
Hello.

I would just like to report I have been getting the Error 
CoreArePluginsReady Failed: (Input Plugin)->IsHooked returned false!

No Rom will launch. 
Im not sure if some where along the line I made a mistake with folders, or something with the Update.
I am running the latest steam deck stable 3.3.2 
RMG has worked for me up until v0.1.9

Thank you very much for your time and consideration.
Cheers!

**Comment by Rosalie241** [comment]
Try switching the input plugin, see settings -> plugins tab, set it to `Rosalie's Mupen GUI - Input Plugin` and that should work.

**Comment by Gilipheoun** [comment]
Oh wow that was really simple. The setting was left blank and I didnt even think to change that. xD
Thank you so much cheers!!

**Comment by Rosalie241** [comment]
I hope you'll enjoy my input plugin, I tried my best! :heart:

**Comment by Gilipheoun** [comment]
I do but please add the ability to make multiple profiles

**Comment by Rosalie241** [comment]
it has per game input profiles, which should be enough I think!

**Comment by Gilipheoun** [comment]
ahh i didnt notice that until now. I was trying to the old way of making it beforehand cheers! The only other thing I would like to recommend would to have extra button inputs. I see an option that allows duplicate inputs. Back buttons on the steam deck would mack great use of this for the c buttons could be the right stick but also be added to X and Y buttons without interfering.

So maybe a couple extra input slots that can be assigned to any button

**Comment by Rosalie241** [comment]
Yes, secondary input bindings have been requested a lot and I want to take a look at that soon-ish, but I've been working on cheat support which is a *lot* of work so far so I'm mainly focused on that :heart:

Thank you for using RMG & giving feedback, it really helps a lot!

**Comment by Gilipheoun** [comment]
OH YES. I had a feeling you've been asked about cheats alot. Ive found a way with a couple games to get them to work but its really hit and miss. Anything built in with passcodes or button presses work fine. but file edits are iffy.

Yes and cheers thank you for the help. Again I run this on the steam deck, and have no issues other than the one just before. but that was a simple setting. and ive done full playthroughs of a few games already.

**Comment by Gilipheoun** [comment]
Z button doesnt show a dot when you press it. Thats the only thing i noticed so far. Not really an issue but since were here just thought I would mention it as im doing controls atm xD

**Comment by thanone2** [comment]
> Try switching the input plugin, see settings -> plugins tab, set it to `Rosalie's Mupen GUI - Input Plugin` and that should work.

how did this work???? it was already set to that then i just re-selected it and it magically works!!
