### ISSUE TITLE
[Feature Request] Add it to the AUR

### ISSUE THREAD

**Issue by Toadfield** [Rosalie241/RMG#7]
I hate compiling myself and I don't like using flatpak as much as the aur.

**Comment by Rosalie241** [comment]
> I hate compiling myself

this really is not my problem.

> I don't like using flatpak as much as the aur.

this also is not my problem.

Whenever I think it's ready, I'll package it as I wish but I'm unsure for now so time will tell.

**Comment by Toadfield** [comment]
ok
