### ISSUE TITLE
Controller detection

### ISSUE THREAD

**Issue by Francehelder** [Rosalie241/RMG#71]
My controller is not detected in RMG 0.2.0
Works fine on RMG 0.1.4, but not on any version above.

My system: Linux

**Comment by Francehelder** [comment]
> So the input device dropdown only shows the keyboard?

Yep
Terminal output

![imagem_2022-12-02_063049291](https://user-images.githubusercontent.com/14970431/205261295-96eae584-9203-492f-9b45-89ccc9d1c53c.png)

**Comment by Rosalie241** [comment]
Can you show a screenshot of the input plugin's window?

**Comment by Francehelder** [comment]
> Can you show a screenshot of the input plugin's window?

![image](https://user-images.githubusercontent.com/14970431/205270149-0df69497-38ec-42ed-a8c8-ec9068644a61.png)

**Comment by Rosalie241** [comment]
Check the 'controller is plugged in' checkbox on the top right, then select your controller from the input device dropdown.

**Comment by Francehelder** [comment]
> Check the 'controller is plugged in' checkbox on the top right, then select your controller from the input device dropdown.

I did try this, but nothing happens.
Controller still not detected.

**Comment by Rosalie241** [comment]
1) you have to restart the game after doing that
2) you have to map each button (so click the buttons next to i,e Up, then press the controller button)

**Comment by Francehelder** [comment]
> 1. you have to restart the game after doing that
> 2. you have to map each button (so click the buttons next to i,e Up, then press the controller button)

1. Done
2. Done

All button mapped, but don't work on the game.

**Comment by Francehelder** [comment]
The A button is the key for play the game. I mapped each button again (A mapped to X button on DualShock 4) and did work. 

In version 0.1.4 no configuration was required.
How can i get the joystick config of this version to use on version 0.2.x?

**Comment by Rosalie241** [comment]
Click on `Up`, then move the joystick up, etc
