### ISSUE TITLE
When entering fullscreen the game screen/window is really small

### ISSUE THREAD

**Issue by RokkumanX** [Rosalie241/RMG#72]
This one is kinda hard to make a capture of but whenever I fullscreen with either angrylion or parallel the output is really small and on top of that the image is not centered but defaults to the lower left of my screen.

This is a mockup screen of how it looks in fullscreen playing something in RMG
![RMG](https://user-images.githubusercontent.com/85066613/207832356-4aec2278-c22e-4911-ac0b-cb1e91680e51.png)

It doesn't matter if I set the resolution to 640x480 or 1920x1080 in angrylion, the output is always the same, a small screen at the lower left.

Am I doing something wrong here? If I don't fullscreen it looks kinda normal and I can kinda get 1920x1080 to work.

I know the information above is kinda vague and not much to go on but I don't have any issues fullscreening with the standalone version of Mupen64Plus (command line) or Simple64.

**Comment by RokkumanX** [comment]
This seems completely resolved in the latest 0.2.5 release, sorry for not testing the latest latest version first instead of the older one I used.

**Comment by Rosalie241** [comment]
It's fine, thank you for using RMG and reporting issues you find :heart:

**Comment by RokkumanX** [comment]
@Rosalie241 

Thank you so very much for all you have done with RMG, in the little time I have known RMG you have done more in such a short time then Project64 ever have done in it's long time and you are almost alone doing it.

If you are an N64 angel fallen from the sky, I sure hope you didn't hurt yourself in the fall.

Have a nice day and continue to shine!
