### ISSUE TITLE
The Toolbar setting is kinda yanked and don't respect setting it to off

### ISSUE THREAD

**Issue by RokkumanX** [Rosalie241/RMG#79]
Hi

First of all I must say that the new GUI overhaul looks spectacular and works great overall but there is one small yankiness with the Toolbar.

When you first start RMG the Toolbar is on by default, if you turn it off it will stay off until either you configure a game directory or start a game and I have to turn it off again.

In the Mupen64Plus.cfg even if the Toolbar is visible in the GUI it says Toolbar = false.

The Statusbar setting is unaffected and works no matter what you do so it's only the Toolbar.

So what I'm kinda expecting is that the Toolbar would respect my decision to be turned off no matter what I do afterwards.

Thanks in advance and have a happy new year!

**Comment by RokkumanX** [comment]
It also seems like the Toolbar is visible in fullscreen mode too which I didn't quite expect.

**Comment by Rosalie241** [comment]
This should fix your issues hopefully: https://github.com/Rosalie241/RMG/actions/runs/3812248896 :heart:

**Comment by RokkumanX** [comment]
You are amazing Rosalie!

I don't think I have a single issue with RMG anymore, everything that I care for works great now.

Have a nice new years eve!

**Comment by Rosalie241** [comment]
Thank you for reporting issues and you have a nice new years eve too :heart:

**Comment by Rosalie241** [comment]
The fix has been included in v0.2.8 :two_hearts:
