### ISSUE TITLE
[Feature Request] Add Screenshots and videos to the Github page

### ISSUE THREAD

**Issue by Toadfield** [Rosalie241/RMG#8]
I mean that there are screenshots and videos of your gui on the github page.
And also,comparisons of your gui and P64 would be cool.

**Comment by Rosalie241** [comment]
> I mean that there are screenshots and videos of your gui on the github page.

this is on my TODO list

> And also,comparisons of your gui and P64 would be cool.

maybe in the future


anyways, I'm on linux mint right now so here's how it looks there:

![image](https://user-images.githubusercontent.com/18737914/108121357-fc9b9680-70a2-11eb-811f-ba399204ff08.png)

![image](https://user-images.githubusercontent.com/18737914/108121392-0ae9b280-70a3-11eb-87b0-d58d7f006302.png)

![image](https://user-images.githubusercontent.com/18737914/108121423-16d57480-70a3-11eb-8c03-736331a5c71c.png)

![image](https://user-images.githubusercontent.com/18737914/108121472-28b71780-70a3-11eb-88df-29f0d2dcb237.png)

![image](https://user-images.githubusercontent.com/18737914/108121537-3a98ba80-70a3-11eb-89bd-fb21977bada3.png)

**Comment by Toadfield** [comment]
ok
