### ISSUE TITLE
Games freezing when using Mupen64 Plus Raphnetraw Input Plugin

### ISSUE THREAD

**Issue by themagpieswarble** [Rosalie241/RMG#80]
I just received my dual N64 Raphnet adapter and am testing it out with RMG. It worked fine when I used Rosalie's default Input and mapped everything manually. However, when I switch to the RaphnetRaw Input that came with the latest version of RMG (updated today to 0.2.9) it freezes up any game I play after about 5-10 seconds. For example, in Smash Bros I can usually get to the character select screen before the game freezes and I have to shut down the rom. With Mario 64, I get to Mario's Face title screen and it freezes. 

I've updated to the latest firmware with the Raphnet adapter as well (3.6.1).  I also just tried Mupen64 Plus GUI (now known as simple64) and the same thing happens there. So, this is perhaps not an emulator issue but still curious if you might have any ideas?

Any ideas?

**Comment by themagpieswarble** [comment]
Nevermind, I believe I figured it out but I want to leave it up here in case someone else runs into it. I had the Raphnet Adapter Manager open. I got the idea to close it while playing when I was trying Project64 and it told me to make sure to close the utility before I could load the Raphnet Raw adapter there. I closed it and went back to RMG and it's working totally fine now.

Thank you!

**Comment by Rosalie241** [comment]
I'm glad you were able to solve the issue yourself, hopefully you'll enjoy using RMG :heart:
