### ISSUE TITLE
Retrolink N64 USB Controller - Incorrectly recognized from Input Plugin

### ISSUE THREAD

**Issue by acepow3r** [Rosalie241/RMG#81]
I have a problem with Retrolink N64 USB Controller. The controller is recognized from Windows 10 as "Generic USB Controller". The buttons work as intended from Windows control panel settings. It also works as intended with Mupen64plus from RetroArch and Project64.

The problem is that RMG Input plugin recognizes the controller as "G-Shark GS-GP702" which is not and treats the A and Z buttons as triggers, thus I cannot make it work correctly because those two buttons appear as constantly pressed.

**Comment by Rosalie241** [comment]
Can you take a screenshot of the configuration window of the input plugin? (Settings -> Input)

**Comment by acepow3r** [comment]
![RMG](https://user-images.githubusercontent.com/24828777/210470954-0ad299a9-916d-486c-8c65-21d727b7828f.jpg)

The Z and A buttons are mapped to the same A and Z buttons of the Retrolink controller and they are shown as lefttrigger+ and righttrigger+ despite they are digital buttons.

Update: I discovered that if I uncheck the option "Invert Axes Mapped To LRZ" then ingame despite that they are shown as triggers, they are working pretty much correctly. So much more this is an annoyance and less of a bug...

**Comment by Yui12** [comment]
I had to do the same thing with my generic usb N64 controller for Z to work as well. Works fine now.

**Comment by Rosalie241** [comment]
Can you try this build: https://github.com/Rosalie241/RMG/actions/runs/4096583401 and see if that fixes it for you?

**Comment by Yui12** [comment]
> Can you try this build: https://github.com/Rosalie241/RMG/actions/runs/4096583401 and see if that fixes it for you?

It works great with my controller thanks.

**Comment by Rosalie241** [comment]
Closing due to it working fine for Yui12, if it still doesn't work, feel free to re-open the issue!
