### ISSUE TITLE
Feature Request: VRU Support

### ISSUE THREAD

**Issue by Bitwolfies** [Rosalie241/RMG#84]
Hi there! Recently there was a[ post on the r/emulation subbreddit ](https://www.reddit.com/r/emulation/comments/101kumh/hey_you_pikachu_vru_mic_emulation_now_possible_no/)making light of the fact that basic VRU support was added to Mupen back in June of last year, with the commenter implying it worked flawlessly in stock Mupen/simple64.

I'm sure you have a lot on your plate, but if the feature is considered working to your standards it would be nice to see it implemented here. (Unless I just really badly missed the toggle for it or something)

Thank you!

**Comment by Rosalie241** [comment]
Implemented, you can try it out with this build: https://github.com/Rosalie241/RMG/actions/runs/5427884920

it'll be included in the next release!

**Comment by Rosalie241** [comment]
Considering the only games supporting the VRU need it plugged into the 4th port, that's where you'll find the VRU option, see the following screenshot:

![image](https://github.com/Rosalie241/RMG/assets/18737914/42c3c84f-877b-44ec-92eb-03fc58e640ce)
