### ISSUE TITLE
[Windows] Issues when maximizing ROM browser and game windows.

### ISSUE THREAD

**Issue by RetraCarteR** [Rosalie241/RMG#88]
I'm running v0.2.9 of RMG on Windows 11, and I've noticed a couple of bugs involving maximizing windows in windowed mode. (By "maximizing a window", I'm referring to the act of clicking the button in the top right corner of the screen next to the "close" button when the window is pulled up but isn't taking up the full screen. This is similar to, but distinct from full screen mode because it doesn't hide the title bar at the top of the screen or the taskbar at the bottom.) Here's what I've noticed:

- When attempting to maximize the window when a game is running in windowed mode, RMG clearly _tries_ to do so, but immediately reverts to a non-maximized window that takes up _most_ of the screen, but not all of it.
- If the ROM browser window is maximized when a game is opened, exiting the game using the "Shutdown" hotkey while it is in full screen mode will cause the ROM browser to be pulled back up in a non-maximized window. This window takes up nearly the entire screen, but it is not maximized (you can still resize the window), and strangely, the title bar is not visible until the window is resized.

I should note that I'm using the default plugins (namely GlideN64 for video), and that these issues occur even when using default settings (I initially had "Automatically Switch To Fullscreen On Emulation Start" turned on, but turning it off doesn't seem to make a difference). It's possible that this might be an issue with GlideN64, in which case I understand that there isn't much you can do about it, but considering that the ROM browser window is affected, I'm inclined to think that the problem is on your end.

I'd like to conclude by saying that I greatly appreciate all of the work you've done to create and maintain RMG. I believe that it's by far the best frontend for Mupen64Plus available today, and I look forward to continuing to use it and see it improve in the coming weeks, months, and hopefully years.

**Comment by Rosalie241** [comment]
>  * When attempting to maximize the window when a game is running in windowed mode, RMG clearly _tries_ to do so, but immediately reverts to a non-maximized window that takes up _most_ of the screen, but not all of it.

I'm sadly unable to reproduce this issue, here's a screenshot of me using RMG with the window (while in-game) maximized:
![image](https://user-images.githubusercontent.com/18737914/213866422-7dfc0373-48a3-4f0a-9173-abbad540d583.png)

I mostly use RMG while having the window maximized in-game on linux so it's really odd you have that issue!

>  * If the ROM browser window is maximized when a game is opened, exiting the game using the "Shutdown" hotkey while it is in full screen mode will cause the ROM browser to be pulled back up in a non-maximized window. This window takes up nearly the entire screen, but it is not maximized (you can still resize the window), and strangely, the title bar is not visible until the window is resized.
> 

I'm also sadly unable to reproduce this issue, for me it returns the ROM browser to a maximized state.

> 
> I'd like to conclude by saying that I greatly appreciate all of the work you've done to create and maintain RMG. I believe that it's by far the best frontend for Mupen64Plus available today, and I look forward to continuing to use it and see it improve in the coming weeks, months, and hopefully years.

Thank you :heart:

**Comment by Rosalie241** [comment]
I've taken a look at the second issue you mentioned and I think I've resolved it, can you test this CI build to see if it also fixes it for you? https://github.com/Rosalie241/RMG/actions/runs/3974812928

**Comment by RetraCarteR** [comment]
I can confirm that the ROM browser issue is now fixed. Thanks for addressing that so quickly!

As for the other issue, I don't know why it's working for you and not for me. Maybe it has something to do with the fact that you're on Windows 10 and I'm on Windows 11? After some more testing, I've noticed that the issue only happens on the GlideN64 video plugin, so it's likely that this particular problem is on their end and not yours. I also noticed that it _does_ let me maximize the window when the emulation is paused, but the second I unpause it, it unmaximizes. And then when I hit the "Shutdown" hotkey, it maximizes again when the ROM browser comes back up. Strange.

Oh well. It's not a deal breaker for me since I mostly play in full screen anyways, and I understand that there's not much you can do without being able to replicate the issue, so don't worry too much about it. Thanks for looking into it anyways; I really appreciate it. And again, I'm looking forward to whatever you have in store next for RMG.

**Comment by Rosalie241** [comment]
After some discussion and help from users from my discord, we found the issue, it's when the following conditions are met:

1) scaling is set to anything bigger than 100%
2) a theme other than the default one is selected

after some trial & error, I've hopefully fixed the issue, please try https://github.com/Rosalie241/RMG/actions/runs/3980842308

I should note however that the theme settings have changed, now you can change the theme in settings -> Interface -> Misc and change the Theme to i.e 'Fusion Dark', then restart RMG!

**Comment by RetraCarteR** [comment]
I tried out the build you posted, and sure enough, it works perfectly now! I always have scaling set to 125% in the Windows settings, so that explains why I was experiencing the issue. Glad to see that you were able to resolve it!
