### ISSUE TITLE
[Feature Request] Netplay Support

### ISSUE THREAD

**Issue by Toadfield** [Rosalie241/RMG#9]
It would be cool if your gui would support the netplay code and gui of [M64P](https://github.com/loganmc10/m64p).

**Comment by Rosalie241** [comment]
Not anytime soon, and considering hosting a server isn't free (and creating a 'local server' feature takes a lot of time), probably never.

**Comment by Calinou** [comment]
For those coming from a web search, netplay support was added in 0.6.8: https://github.com/Rosalie241/RMG/releases/tag/v0.6.8
