### ISSUE TITLE
[Feature Request] 7z

### ISSUE THREAD

**Issue by AngryScotsmanGaming** [Rosalie241/RMG#90]
Since 7z is the best form of compression and I know a lot of people try to keep all their file formats the same would it be possible for 7z to be implemented? Also doing a great job keep it up!

**Comment by daemonlinux88** [comment]
COD WarZone DJ Cummerbund - The Next Sickness.m...
<https://drive.google.com/file/d/1NWrdu4dV9-cuziIPB81__dvEaEbmQ5_Y/view?usp=drive_web>

**Comment by Rosalie241** [comment]
You've already requested this feature in https://github.com/Rosalie241/RMG/issues/63.
