### ISSUE TITLE
Running ROM from CLI uses wrong directory

### ISSUE THREAD

**Issue by scurest** [Rosalie241/RMG#91]
When passing a ROM to play on the CLI, it appears to treat the path as relative to the location of the RMG binary instead of the current dir (perhaps it's changing cwd?). The error is

> EmulationThread::run Failed  
> read_raw_file Failed: failed to open file: No such file or directory (2)

Example

```sh
# This should work but doesn't
~ RMG-Portable-Linux64-v0.2.9/RMG roms/n64/some_rom.z64

# Absolute path works
~ RMG-Portable-Linux64-v0.2.9/RMG ~/roms/n64/some_rom.z64

# Path relative to RMG binary works
~ RMG-Portable-Linux64-v0.2.9/RMG ../roms/n64/some_rom.z64
```

**Comment by Rosalie241** [comment]
That's expected behavior for portable installs, if you'd like it to not change the current directory for the application, you can either use the flatpak or package it for your distribution.
