### ISSUE TITLE
Controller input able to open emulator dialogs

### ISSUE THREAD

**Issue by Luctaris** [Rosalie241/RMG#92]
Occasionally while pressing configured L+R+Z input buttons at the same time, the emulator's Cheats dialog pops up. My input for L, R, and Z triggers was bound to the C, V, and B key on my keyboard. I am using RMG 0.3.0 on Debian Testing.

I suspect this is because the current input handling implementation probably adds up the value of keys and makes a decision on what action to perform, in this case (V+B = value for Ctrl. Ctrl+C = opens cheat dialog)

**Comment by Rosalie241** [comment]
I'm unable to reproduce this and I have no clue how or why that'd happen, as a workaround you can try to change the hotkey for i.e the cheats menu.

**Comment by Luctaris** [comment]
After some further testing, I'm having trouble re-creating this issue on most N64 games. It seems that it only happens on a handful of games with a lot of lag present, and even then I have to go out of my way to get the dialog to show up. 

Changing the hotkeys to something else seemed to have fixed it, so I'll go ahead and close out this issue.
