### ISSUE TITLE
[Feature Request] Automatically Assign Joystick Ports

### ISSUE THREAD

**Issue by Sterophonick** [Rosalie241/RMG#93]
I use RMG on the Steam Deck, and it would be nice if the new input plugin automatically assigned ports to attached joysticks based on their SDL2 gamepad port number.

**Comment by Rosalie241** [comment]
Can you be more specific in what you want? I'm having difficulties understanding the feature request sadly.

**Comment by Sterophonick** [comment]
The Qt input plugin in Mupen64Plus is a good example.
![image](https://user-images.githubusercontent.com/34801996/215636143-f873818d-5c74-4425-8c4f-a9028385d161.png)

There's an option under `Gamepad` labeled as `Auto`. This option will automatically attach controllers to their respective ports. 

For example:
If I have one controller attached to the host, there will be a single controller attached to the emulated N64. If I have two attached to the host, there will be controllers attached to ports one and two of the emulated N64. If I were to detach one of these controllers, the emulator automatically detaches the respective controller port from the guest machine. 

This behavior makes multiplayer sessions much more convenient, as I don't need to manually attach the controllers to their ports using a mouse and keyboard, I can just boot up the emulator and start playing.

**Comment by Rosalie241** [comment]
I should probably mention I've been working on it, when it's finished, I'll make a new release with it :heart:

**Comment by Rosalie241** [comment]
Implemented in v0.3.3 :two_hearts:

**Comment by Sterophonick** [comment]
Fantastic! Thank you so much! ❤️
