### ISSUE TITLE
Input Profiles Issue (?)

### ISSUE THREAD

**Issue by gumbucc** [Rosalie241/RMG#94]
I can't seem to add a new input profile. When I click on the input profiles button in the controller configuration menu, it just shows the "main" profile. 
![screen](https://user-images.githubusercontent.com/114039424/215618813-d3293ad4-c1fc-4388-a470-bb1150eb2f1d.png)
As you can see, I clicked on the profiles button and it only showed the main profile, no option to add a new one.
I am using the flatpak on flathub, on 0.3.0, and on Linux Mint 21.1

**Comment by Rosalie241** [comment]
Currently RMG-Input only supports per-game input profiles, when you're in a game and open the input settings, the game specific input profile will be available.

**Comment by gumbucc** [comment]
> Currently RMG-Input only supports per-game input profiles, when you're in a game and open the input settings, the game specific input profile will be available.
That explains that, although it would be a nice feature to have input profiles independent of games.

**Comment by Rosalie241** [comment]
I'll add it to my long-term TODO list :heart:
