### ISSUE TITLE
[Feature Request] Add glide64 GFX plugin

### ISSUE THREAD

**Issue by crashGG** [Rosalie241/RMG#95]
It would be great if RMG did add glide64 GFX plugin .An example: pj64 incorporates glide64 into itself and renamed glide64 to Project64-video.

After a lot of testing, this plugin has the fastest speed on low-end computers, especially with intel integrated graphics cards, which can run at 1080p 60fps.

**Comment by Rosalie241** [comment]
No, I refuse to add unmaintained and legacy plugins but you're free to build it yourself locally and add the plugin to `Plugin/GFX`.

**Comment by Rosalie241** [comment]
After a quick look of the source code, see <https://github.com/mupen64plus/mupen64plus-video-glide64/blob/master/src/Main.cpp#L997>, it requires `GLide64.ini` to be in the `Data` directory.

**Comment by crashGG** [comment]
> After a quick look of the source code, see https://github.com/mupen64plus/mupen64plus-video-glide64/blob/master/src/Main.cpp#L997, it requires `GLide64.ini` to be in the `Data` directory.

Thank you for your hint,when GLide64.ini in the Data directory, the glide64 plungin works.But now there is a new problem, RMG cannot set the plugin, the Graghics Setting is always gray.
<img width="448" alt="2023-02-04_110448" src="https://user-images.githubusercontent.com/80488411/216756618-b2428c22-6ad8-436c-a543-2fa683d9d2a7.png">

**Comment by Rosalie241** [comment]
That's expected because glide64 doesn't have a configuration GUI in the mupdn64plus version, you'll have to edit the configuration file manually.
