### ISSUE TITLE
Trigger buttons on controllers (Xbox and Non-Xbox Controllers) not working after mapping

### ISSUE THREAD

**Issue by Relat1v1ty** [Rosalie241/RMG#96]
It is possible to map the Z-Trigger to either of the USB controller's trigger buttons, but they will not work any time after that.
This is true for both Xbox Controllers (that use XInput) and Non-Xbox Controllers (That use DirectInput). I tried both.

See below, the Z-Trigger can be mapped to axis 5- (which is the Right Trigger of this controller), but after mapping, pressing the controller's Right Trigger does not work again afterward.
![image](https://user-images.githubusercontent.com/121585717/216844950-7db84e33-c25c-4a88-a64e-f2e6faa2d961.png)

![image](https://user-images.githubusercontent.com/121585717/216845356-e0ef433a-6be1-4867-b7f9-b7c93f0bc70c.png)

**Comment by Rosalie241** [comment]
I've hopefully fixed this issue earlier today, try this build: https://github.com/Rosalie241/RMG/actions/runs/4098133168

**Comment by Relat1v1ty** [comment]
Hi there, this is awesome, thank you, you certainly did fix it, the right trigger does work now after mapping!
But, another problem has now presented itself though (I'm sorry) - the right analogue stick cannot map left and right on Non-Xbox controllers (DirectInput).

The capture below is of me trying to map left and right on the right analogue stick, but RMG does not see it...
![image](https://user-images.githubusercontent.com/121585717/216845838-b3639429-26e4-41f5-922a-ccbc9d591e5a.png)

Note: Everything seems to work A-OK though for Xbox controllers (XInput).

**Comment by Rosalie241** [comment]
Does https://github.com/Rosalie241/RMG/actions/runs/4104773977 fix that issue?

**Comment by Relat1v1ty** [comment]
Yes! It does work indeed.
Thank you! 
I'm not sure if I'm doing the right thing, but I shall, 'Close with Comment'.

**Comment by Rosalie241** [comment]
Fix has been included in v0.3.2 :heart:
