### ISSUE TITLE
Auto update doesn't work

### ISSUE THREAD

**Issue by Tasosgemah** [Rosalie241/RMG#97]
When i open the emulator the auto-update message appear and asks me to update if i want.

I do choose to update and the process starts. It downloads the files and i see the extraction process. Then the emulator restarts. But the version is the same like i had before and the updater asks me to update again. If i do, the same happens again so it's a never ending circle.

**Comment by Rosalie241** [comment]
Can you try this build to see if that works? https://github.com/Rosalie241/RMG/actions/runs/4145212004

I'd recommend placing it in the same location to test it properly.

**Comment by Tasosgemah** [comment]
Yeah, that one updated successfully.

**Comment by Rosalie241** [comment]
Thank you, it'll be included in the next release, though note that you'll still need to update to that release manually then, but from then on you should be fine!

**Comment by Tasosgemah** [comment]
Ok, im closing this then, thanks
