### ISSUE TITLE
[Feature Request] Analog Sensitivity

### ISSUE THREAD

**Issue by Flax4** [Rosalie241/RMG#98]
Would it be possible to have a setting for changing analog sensitivity? I've been using Simple64 but found this and I love it but that is one feature that was quite nice on Simple64.

Totally cool if there is no plans for this, still loving RMG for all the options and clean user interface!

Image for reference:
![image](https://user-images.githubusercontent.com/50862920/217251316-102116b8-38b3-4248-8e45-d14a3851e02a.png)

**Comment by RadikAlice** [comment]
Would be nice indeed, could also maybe work as an equivalent to the "Real N64 Range" toggle
on the N-Rage input plugin for Project64, N64 accuracy would be ideal.
But a plain sensitivity slider would be completely welcome, RMG Input is close to perfect to me

**Comment by Rosalie241** [comment]
This has been implemented by @JaxonWasTaken and will be included in the next release!

**Comment by RadikAlice** [comment]
> This has been implemented by @JaxonWasTaken and will be included in the next release!

Cheers to them! RMG is now one step closer to further greatness and usability
Having no idea about the backend, I just agreed in hopes it was possible
I rightfully assumed in my head that it wouldn't be as simple as hooking into an existing setting in mupen64plus-input

**Comment by Rosalie241** [comment]
Implemented in v0.3.9
